/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const createRef: typeof import('react')['createRef']
  const forwardRef: typeof import('react')['forwardRef']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const startTransition: typeof import('react')['startTransition']
  const useCallback: typeof import('react')['useCallback']
  const useClassnames: typeof import('../frame/hooks/useBasic')['useClassnames']
  const useContext: typeof import('react')['useContext']
  const useCookie: typeof import('../frame/hooks/useCookie')['useCookie']
  const useCss: typeof import('../frame/hooks/useCss')['useCss']
  const useDay: typeof import('../frame/hooks/useBasic')['useDay']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useEnv: typeof import('../frame/hooks/useEnv')['useEnv']
  const useFetch: typeof import('../frame/hooks/useFetch')['useFetch']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useMemo: typeof import('react')['useMemo']
  const useMessage: typeof import('../frame/hooks/useBasic')['useMessage']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
}
